parameters:
    stripe.secret_key: '%env(STRIPE_SECRET_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $stripeSecretKey: '%stripe.secret_key%'  # ✅ ici c’est corrigé

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\StripeCheckoutService:
        arguments:
            $stripeSecretKey: '%stripe.secret_key%'  # ✅ ici aussi
