version: '3.9'

services:

  mysql-t:
    image: mysql:8
    container_name: mysql-t
    environment:
      MYSQL_DATABASE: tricot
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: tricot123
      MYSQL_PASSWORD: tricot
    # ports:
    #   - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - t-network


  symfony-backend-t:
    build: ./backend
    container_name: symfony-backend-t
    volumes:
      - ./backend:/var/www/t
      - ./backend/config/jwt:/var/www/t/config/jwt 
    environment:
      APP_ENV: dev
      APP_DEBUG: 1  
    ports:
      - "9030:9000"
    networks:
      - t-network

  react-frontend-t:
    build:
      context: ./frontend
    container_name: react-frontend-t
    volumes:
      - ./frontend:/app
    ports:
      - "3030:3000"
    command: npm start  
    stdin_open: true
    tty: true
    networks:
      - t-network
   

  nginx-t:
    image: nginx:stable
    container_name: nginx-t
    ports:
      - "90:80" 
    volumes:
      - ./backend/public:/var/www/t/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - symfony-backend-t
      - react-frontend-t
    networks:
      - t-network

networks:
  t-network:
    driver: bridge

volumes:
  mysql-data: